### ISSUE TITLE
File not found in 2.0.5

### ISSUE THREAD

**Issue by thomas2403** [bpellin/keepassdroid#82]
After the update to 2.0.5 I tried to open the database file and got "File not found". The file is synced by the Owncloud client and has special characters in its path. 
/storage/emulated/0/owncloud/thomas@xyz.abc.de%3A1111/ownCloud/keepass/kp2.kdbx

I've tried to replace @ with %40, didn't change anything. It went fine with 2.0.4.

**Comment by bpellin** [comment]
How do you enter the filename into Keepassdroid? Do you click on the file
from another app, use the browse folder within Keepassdroid and use another
app to select it, or some other method?

**Comment by thomas2403** [comment]
I open Keepassdroid and select the file by the open button with either Solid Explorer or the CM File Explorer. The result is the same, file not found. 
I also tried to open the database file by clicking on it in Solid Explorer without having Keepassdroid started. In that case I get an EBADF error in Keepassdorid. 
FYI, I switched back to 2.0.4 this morning, everything is fine now.

**Comment by bpellin** [comment]
I believe I have fixed these issues in the latest beta. Can you try it and let me know if this resolves the EBADF issue:
https://play.google.com/apps/testing/com.android.keepass

**Comment by thomas2403** [comment]
Sorry, it's still not working. Now I always get the EBADF error (bad file number). It doesn't matter, if I select file file from inside the app or form Solid Explorer without having the app started. But I don't get "File not found" errors anymore.
![screenshot_2016-03-15-10-14-27](https://cloud.githubusercontent.com/assets/17723660/13772905/e370e6ca-ea96-11e5-9f7c-cdb168be0d83.png)

**Comment by thomas2403** [comment]
I kept on trying, it has nothing to do with the file path anymore. You replaced @ with %40 and % with %25, that looks right to me. That's why I copied both files, database and key to /storage/emulated/0/ (root of the internal memory), same error. It looks like Keepassdroid can't read that file at all. I went back to 2.0.4, no problems.

**Comment by bpellin** [comment]
Key file handling should be fixed in 2.0.6 which is rolling out now.
